### ISSUE TITLE
WEBIRC support

### ISSUE THREAD

**Issue by hef** [hef/IRCTransport#22]
There is an extension to IRC that allows mibbit to forward the users real hostname to the irc server.

[specification](http://wiki.mibbit.com/index.php/WebIRC)
[Forum request](http://forums.bukkit.org/threads/chat-irctransport-0-10-minecraft-chat-irc-integration-1060.3412/page-5#post-679361)

**Comment by ghost** [comment]
It seems your plugin supports cgiirc (webirc) as there is a
server:
  webirc_password:

directive, but it seems that it does nothing.
setting verbose to true doesnt show the WEBIRC directive to be sent.

**Comment by Marlinc** [comment]
I would really like this function because then I have better control on the server

**Comment by hef** [comment]
It's undocumented in version 0.12.0 and official in 0.13.0-SNAPSHOT. This feature will officially be in 0.13.0.
