### ISSUE TITLE
IRC Whois or another global command?

### ISSUE THREAD

**Issue by kolorafa** [hef/IRCTransport#23]
I have just installed your plugin, but i see that players can change nick as they want, so when someone new comes you cannot check what is the player real name from game or from irc channel.

Can you add:
-some extra info about player (login?) in /whois in some fields
-add /whois command or global /irc command that pass evrything to serwer?
-add some commands to identify yourself in nickserv :) (or use global /irc msg nickserv id PASS)

**Comment by hef** [comment]
I can add a `whois` command, that seems useful

When a player signs into IRC, the irc "username" is still their minecraft name, even after a nick change, you can see this from another irc client, but not yet ingame.  I'll work on that.

you should be able to `/msg nickserv identify password` already

**Comment by hef** [comment]
whois command added in version 0.11
