### ISSUE TITLE
Multiple prefixes/nicknames on used?

### ISSUE THREAD

**Issue by kolorafa** [hef/IRCTransport#24]
Ability to put multiple pre/sufixes to be able to use that nick even when someone else use it.

For example, you have name "test" but user named "test" is already online on irc, so like any other irc client it will use alternative for example test_ or test_sufix.

(because i'm connecting to my friend irc server,  and sometimes i'm left with nick used and then players gets "ircBot" name instead and even don't join channel, and they don't usually know how to fix it.

Or maybe option to set autojoin on invite :)

**Comment by hef** [comment]
This feature should work already, It's not confugurable though.  Currently, it will append a number to the end of your nick if the nick is already in use.

If this isn't working, let me know.
